### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by 13abylon** [poojan/gitbook-plugin-toggle-chapters#1]
This is a great plugin! I think you totally need toggled chapters for the gitbook.

Only problem, with the new gitbook Version (2.0) it seems the plugin isnt working.

Is it planned to be updated, so it works with the new gitbook version?

**Comment by poojan** [comment]
Removed deprecated hooks on 3d8f2aa9b411100a2faf41df0b6367957ecb46ec

So you won't see those warnings now. However, the plugin seemed to be otherwise working for me on Gitbook 2.0. 

Anyway, I hope this fixes it for you. Cheers. :-)

**Comment by 13abylon** [comment]
Thanks for the fast response! :)

The warning are gone, the plugin still doesn't work for me :( My chapters are all closed and I can't open them with a click.

Is there maybe something I forgot to set up?

**Comment by poojan** [comment]
This screenshot should give you an idea of all the steps I took to run it, my gitbook-cli and gitbook versions and the browser console output. 

Do you have any errors on the browser console? Also, could you give me an idea or your steps?

![screen shot 2015-05-19 at 14 59 15](https://cloud.githubusercontent.com/assets/150326/7699495/f8f15760-fe37-11e4-9108-2530cded4cff.png)

**Comment by 13abylon** [comment]
I've done it like you and it works!

However, if I create the gitbook via `gitbook build` the plugin does not work.

If I type `gitbook serve .` it does work without problems

**Comment by 13abylon** [comment]
Okay, I've found a difference:

![image](https://cloud.githubusercontent.com/assets/1833374/7700272/c8308b38-fe1d-11e4-9d78-
1bd5a89f2d25.png)

Thats how it looks if I `build` it via gitbook:

```
navigate to /dir1/dir2/file.html
```

If I `serve` it via gitbook it looks like this:

```
navigate to /dir2/file.html
```

Could it be that the Plugin have problems if there is one folder more to navigate to?

**Comment by poojan** [comment]
Yes. That was the case. 

24c1ad8edb9f48d4d7b884eafa529f509a25ae4a should fix it.

**Comment by 13abylon** [comment]
Yes, this is the fix.

Thank you very much :) :+1:
